version: '3'
services:
  nginx:
    image: nginx:1.15.0
    container_name: server_nginx
    ports:
      - "8002:8000"
    volumes:
      - ./src/server:/src
      - ./src/server/app/static:/data/static
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  web:
    build: ./docker
    image: surgerymumc/webapp-template:latest
    container_name: server_web
    command: /src/docker-entrypoint.sh
#    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn l3bodycomp.wsgi -b 0.0.0.0:8001 -t $WORKER_TIMEOUT"
    environment:
      - ROOT_DIR=/data
      - SECRET_KEY=1234
      - DOCKER
      - WORKER_TIMEOUT
    volumes:
      - ./src/l3bodycomp:/src
      - data:/data
    depends_on:
      - db
  redis:
    restart: always
    image: redis:6.2.5
    container_name: l3bodycomp_redis
    command: bash -c "redis-server"
    ports:
      - "6379:6379"
  rq:
    restart: always
    image: surgerymumc/webapp-template:latest
    container_name: server_rq
    command: bash -c "export CUDA_VISIBLE_DEVICES=1 && python manage.py rqworker"
    environment:
      - ROOT_DIR=/data
      - SECRET_KEY=1234
      - DOCKER
      - WORKER_TIMEOUT
    volumes:
      - ./src/server:/src
      - data:/data
    depends_on:
      - db
      - redis
  db:
    restart: always
    image: postgres:10.5-alpine
    container_name: server_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
volumes:
  data:
    driver: local
  postgres_data:
    driver: local
