version: '3'
services:
  nginx:
    image: nginx:1.15.0
    container_name: server_nginx
    ports:
      - "8002:8000"
    volumes:
      - ./src/server:/src
      - ./src/server/app/static:/data/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  web:
    build: .
    image: surgerymumc/webapp-template:latest
    container_name: server_web
    command: bash -c "/docker-entrypoint.sh"
    environment:
      - ROOT_DIR
      - SECRET_KEY
      - ALLOWED_HOSTS
      - DEBUG
      - WORKER_TIMEOUT
      - POSTGRES_HOST
      - REDIS_HOST
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - ./src/server:/src
      - data:/data
    depends_on:
      - db
  redis:
    restart: always
    image: redis:6.2.5
    container_name: server_redis
    command: bash -c "redis-server"
    ports:
      - "6379:6379"
  rq:
    restart: always
    image: surgerymumc/webapp-template:latest
    container_name: server_rq
    command: bash -c "export CUDA_VISIBLE_DEVICES=1 && python manage.py rqworker"
    environment:
      - ROOT_DIR
      - SECRET_KEY
      - ALLOWED_HOSTS
      - DEBUG
      - WORKER_TIMEOUT
      - POSTGRES_HOST
      - REDIS_HOST
    volumes:
      - ./src/server:/src
      - data:/data
    depends_on:
      - db
      - redis
  db:
    restart: always
    image: postgres:10.5-alpine
    container_name: server_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
volumes:
  data:
    driver: local
  postgres_data:
    driver: local
