# Generated by Django 3.2.3 on 2021-10-19 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('zip_path', models.CharField(max_length=1024, null=True)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('parameters', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.CharField(max_length=128, null=True)),
                ('job_status', models.CharField(max_length=16, null=True)),
                ('errors', models.CharField(max_length=2048, null=True)),
                ('info', models.CharField(max_length=2048, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.datasetmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FilePathModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2048)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.datasetmodel')),
            ],
        ),
    ]
