# Generated by Django 3.2.3 on 2021-09-30 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='job_status',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.taskresultmodel'),
        ),
    ]
