# Generated by Django 3.2.3 on 2021-10-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='error_message',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
