# Generated by Django 3.2.9 on 2021-11-02 20:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), null=True, size=None),
        ),
    ]
