# Generated by Django 3.2.3 on 2021-09-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210930_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='result',
        ),
        migrations.DeleteModel(
            name='TaskResultModel',
        ),
    ]
