# Generated by Django 3.2.3 on 2021-09-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210930_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='task_type',
        ),
    ]
