# Generated by Django 3.2.3 on 2021-10-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_filepathmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
