# Generated by Django 3.2.3 on 2021-10-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_filemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='info_message',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
