# Generated by Django 3.2.3 on 2021-10-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_taskmodel_info_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='zip_file_path',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
