# Generated by Django 3.2.3 on 2021-10-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_datasetmodel_zip_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='parameters',
            field=models.JSONField(null=True),
        ),
    ]
